### ISSUE TITLE
Optimize set of Jupyterhub pod resource requirement options based on team usage 

### ISSUE THREAD

**Issue by MichaelClifford** [aicoe-aiops/operate-first-jupyterhub-analysis#12]
@tumido has identified that the default resources requests for the 4 tiers of Jupyterhub pod configurations do not correspond well to actual usage. This has lead to over commitment of cluster resources that aren't actually being used and impacted cluster performance. See this issue for further details: https://github.com/operate-first/blueprint/issues/83

There is an opportunity for significant improvement in overall cluster performance if we can redefine the pod resource tiers based on actual usage by our data science team. 

We should use the available Prometheus metrics for the JH pods, giving special attention to the metrics shown on [this dashboard](https://grafana-route-opf-monitoring.apps.zero.massopen.cloud/d/GGgK4Q9Mk/tcoufal-testing-total-cpu-usage-vs-request?orgId=1), to provide a data driven recommendation for the optimized resource tiers.   

Acceptance Criteria:

- [x] Notebook that analyzes historical Jupyter pod usage and recommends an new set of resource tiers
- [x] Recommended tiers are incorporated into operate first ODH deployment

**Comment by Shreyanand** [comment]
Tiers available at this JH [instance](https://jupyterhub-opf-jupyterhub.apps.smaug.na.operate-first.cloud).
